docs(configuration): add example for loader option
webpack/webpack.js.org pull request #3927
Opened 2020-08-23 05:20 UTC by chenxsan

2020-08-25 10:44 UTC, montogeek approved these changes

2020-08-28 15:39 UTC, EugeneHlushko requested changes

2020-08-28 15:39 UTC, EugeneHlushko commented on src/content/configuration/other-options.md
> +
Maybe prefix it with `custom-loader.js` or smth like that for more clarity?

2020-08-28 15:39 UTC, EugeneHlushko commented on src/content/configuration/other-options.md
> +T> You can override any properties in loader context as webpack copies all properties defined in `loader` to the loader context.
some grammar suggestion:
```suggestion
T> You can override properties in the loader context as webpack copies all properties that are defined in the `loader` to the loader context.
```

2020-08-31 19:02 UTC, EugeneHlushko requested changes
did i miss them first time or were they added later? sorry if missed

2020-08-31 19:02 UTC, EugeneHlushko commented on src/content/configuration/other-options.md
> +For example, you can define a new variable in loader context:
```suggestion
For example, you can define a new variable in the loader context:
```

2020-08-31 19:02 UTC, EugeneHlushko commented on src/content/configuration/other-options.md
> +Then use `this.answer` to get its value in loader:
```suggestion
Then use `this.answer` to get its value in the loader:
```

2020-10-10 08:13 UTC, sokra approved these changes

2020-10-10 08:14 UTC, merged

2020-10-10 08:14 UTC, sokra commented
Thanks