config : specify default about optimization.nodeEnv
webpack/webpack.js.org pull request #3931
Opened 2020-08-24 20:53 UTC by jeffin143

Refer : https://github.com/webpack/webpack/blob/65710679fbb46534ada2ea93257bbfea573fc288/lib/config/defaults.js#L695-L698

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].

2020-08-25 10:47 UTC, montogeek commented on src/content/configuration/optimization.md
> +T> When [mode](/configuration/mode/) is to `none`, `optimization.nodeEnv` defaults to `false`.
```suggestion
T> When [mode](/configuration/mode/) is set to `none`, `optimization.nodeEnv` defaults to `false`. 
```
```suggestion
T> When [mode](/configuration/mode/) is `none`, `optimization.nodeEnv` defaults to `false`. 
```

2020-08-28 15:29 UTC, EugeneHlushko requested changes

2020-08-28 15:29 UTC, EugeneHlushko commented on src/content/configuration/optimization.md
> +T> When [mode](/configuration/mode/) is to `none`, `optimization.nodeEnv` defaults to `false`.
string is missing quotes (yeah and "set")
```suggestion
T> When [mode](/configuration/mode/) is set to `'none'`, `optimization.nodeEnv` defaults to `false`. 
```

2020-09-19 06:54 UTC, EugeneHlushko approved these changes

2020-09-19 07:08 UTC, merged

2020-09-19 07:08 UTC, EugeneHlushko commented
Thanks!