docs(configuration): specify default value as part of type information
webpack/webpack.js.org pull request #3935
Opened 2020-08-25 17:05 UTC by jamesgeorge007

webpack defaults to `production` mode.

2020-08-26 10:54 UTC, montogeek approved these changes

2020-08-28 15:26 UTC, EugeneHlushko requested changes
if we are doing this, can you also change all similar occurances in one PR? There at least 5-6 places i've seen this

2020-09-11 18:13 UTC, EugeneHlushko approved these changes
will do a follow up to not hold this off

2020-09-11 18:13 UTC, merged

2020-09-11 18:13 UTC, EugeneHlushko commented
Thanks!

2020-09-11 18:19 UTC, EugeneHlushko commented
Hmm this is actually tricky, @montogeek there are places where we say 

By default `optimization.x` is enabled in `production` [mode](/configuration/mode/) and disabled elsewise.

i think it might be useful for people to understand that in dev mode it all might be different... maybe this should be reverted after all?