docs: externalsPresets option
webpack/webpack.js.org pull request #3974
Opened 2020-09-14 07:16 UTC by pranshuchittora

Closes #3965

2020-09-14 07:23 UTC, anshumanv commented
@pranshuchittora I started working on it https://github.com/webpack/webpack.js.org/issues/3965#issuecomment-691865456, no worries though, be mindful from next time :)

2020-09-14 07:24 UTC, pranshuchittora commented
Pardon, didn't saw that.

2020-09-19 07:04 UTC, EugeneHlushko requested changes

2020-09-19 07:04 UTC, EugeneHlushko commented on src/content/configuration/externals.md
> +W> Previously the following functionality was be achieved using `target`.
```suggestion
W> In earlier webpack versions, the following functionality was achieved using [`target`](/configuration/target/).
```

2020-09-19 07:04 UTC, EugeneHlushko commented on src/content/configuration/externals.md
> +`webAsync`     | Treat references to 'http(s)://...' and 'std:...' as external and load them via async import() when used __(Note that this external type is an async module, which has various effects
```suggestion
`webAsync`     | Treat references to 'http(s)://...' and 'std:...' as external and load them via `async import()` when used __(Note that this external type is an `async` module, which has various effects on the execution)__.| boolean
```

2020-09-19 07:04 UTC, EugeneHlushko commented on src/content/configuration/externals.md
> +Using `node` preset will not bundle built-in modules and treats them as external and loads them externally.
```suggestion
Using `node` preset will not bundle built-in modules and treats them as external and loads them via `require()` when used.
```

2020-09-19 07:04 UTC, EugeneHlushko commented on src/content/configuration/externals.md
> +    node:true
```suggestion
    node: true
```

2020-09-27 07:04 UTC, merged

2020-09-27 07:04 UTC, EugeneHlushko commented
Thanks!