fixes #3940: document changes to several config options
webpack/webpack.js.org pull request #3986
Opened 2020-09-18 15:26 UTC by anshumanv

fixes #3940

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-09-30 10:07 UTC, montogeek commented on src/content/configuration/entry-context.md
> +      dependOn:'shared',
```suggestion
      dependOn: 'shared',
```

2020-09-30 10:07 UTC, montogeek commented on src/content/configuration/output.md
> +The method of loading chunks (methods included by default are 'jsonp' (web), 'importScripts' (WebWorker), 'require' (sync node.js), 'async-node' (async node.js), but others might be added by plugins)
```suggestion
The method to load chunks (methods included by default are 'jsonp' (web), 'importScripts' (WebWorker), 'require' (sync node.js), 'async-node' (async node.js), but others might be added by plugins).
```

2020-09-30 10:08 UTC, montogeek commented on src/content/configuration/output.md
> +When targeting a library, especially when `libraryTarget` is `'umd'`, this option indicates what global object will be used to mount the library. To make UMD build available on both browsers and Node
```suggestion
When targeting a library, especially when `libraryTarget` is `'umd'`, this option indicates what global object will be used to mount the library. To make UMD build available on both browsers and Node.js, set `output.globalObject` option to `'this'`. Defaults to `self` for Web-like targets.
```

What are the Web like targets?

2020-09-30 10:09 UTC, montogeek commented on src/content/configuration/output.md
> +- [`output.chunkLoadingGlobal`](/configuration/output/#outputChunkLoadingGlobal)
Please remove one

2020-10-07 11:49 UTC, sokra requested changes

2020-10-07 11:49 UTC, sokra commented on src/content/configuration/output.md
> +`boolean = false` `string: 'array-push' | 'commonjs' | <any string>`
```suggestion
`false` `string: 'array-push' | 'commonjs' | <any string>`
```

2020-10-07 11:49 UTC, sokra commented on src/content/configuration/output.md
> +`boolean = false` `string: 'jsonp' | 'import-scripts' | 'require' | 'async-node' | <any string>`
```suggestion
`false` `string: 'jsonp' | 'import-scripts' | 'require' | 'async-node' | <any string>`
```

2020-10-07 11:49 UTC, sokra commented on src/content/configuration/output.md
> +`[string]` `string: 'jsonp' | 'import-scripts' | 'require' | 'async-node' | <any string>`
```suggestion
`[string: 'jsonp' | 'import-scripts' | 'require' | 'async-node' | <any string>]`
```

2020-10-07 11:49 UTC, sokra commented on src/content/configuration/output.md
> +- [`output.chunkLoadingGlobal`](/configuration/output/#outputChunkLoadingGlobal)
```suggestion
```

2020-10-07 11:51 UTC, sokra approved these changes

2020-10-07 11:52 UTC, anshumanv commented
Oops missed this, thanks for applying suggestions @sokra! 🎉

2020-10-07 12:45 UTC, sokra requested changes

2020-10-07 12:45 UTC, sokra commented on src/content/configuration/output.md
> +- [`output.chunkLoadingGlobal`](/configuration/output/#outputChunkLoadingGlobal)
```suggestion
- [`output.chunkLoadingGlobal`](/configuration/output/#outputchunkloadingglobal)
```

2020-10-07 12:45 UTC, sokra commented on src/content/configuration/output.md
> +For details see [`output.chunkLoadingGlobal`](#outputChunkLoadingGlobal).
```suggestion
For details see [`output.chunkLoadingGlobal`](#outputchunkloadingglobal).
```

2020-10-07 14:48 UTC, sokra approved these changes

2020-10-07 14:48 UTC, merged