Fixing the grammatical errors in the configuration files
webpack/webpack.js.org pull request #3996
Opened 2020-09-22 12:56 UTC by Cronus1007

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2020-09-30 10:00 UTC, montogeek commented
Please revert `node-sass` change.

2020-10-02 10:18 UTC, Cronus1007 commented
@montogeek  I have added the Node-Sass Plugin Concept to the documentation.Please review the PR .

2020-10-07 13:39 UTC, snitin315 requested changes

2020-10-07 13:39 UTC, snitin315 commented on package.json
> +    "node-sass": "^4.14.1",
unnecessary change, please revert.

2020-10-07 13:39 UTC, snitin315 commented on src/content/plugins/index.md
> +| Name                                                                              | Description                                                                            |
looks like a conflict?

2020-10-08 13:40 UTC, closed without merging