Added browserslist output.target and output.environment
webpack/webpack.js.org pull request #4016
Opened 2020-09-30 16:11 UTC by smelukov

Added browserslist output.target and output.environment
closes #4009

2020-10-07 08:34 UTC, EugeneHlushko requested changes

2020-10-07 08:34 UTC, EugeneHlushko commented on src/content/configuration/target.md
> +`string` `function (compiler)` = `"browserslist"` or `"web"` if no browserslist-config found
complex, conditional default should in the description
```suggestion
`string` `function (compiler) => string`
```

2020-10-07 08:34 UTC, EugeneHlushko commented on src/content/configuration/target.md
>  Instructs webpack to target a specific environment.
```suggestion
Instructs webpack to target a specific environment. Defaults to `'browserslist'` or to `'web'` when no browserslist-config was found.
```

2020-10-07 09:55 UTC, sokra commented
@smelukov hey cool to see to working on that. Do you want to merge the other `target` changes into the PR?

see https://github.com/webpack/webpack.js.org/issues/3968

2020-10-07 10:00 UTC, smelukov commented
@sokra ok, I'll do it on this PR ;)

2020-10-07 10:19 UTC, sokra commented
Cool thanks

2020-10-07 15:41 UTC, montogeek commented on src/content/configuration/target.md
> +- determinate ES-features that may be used to generate a runtime-code (all the chunks and modules are wrapped by runtime code).
```suggestion
- Determinate ES-features that may be used to generate a runtime-code (all the chunks and modules are wrapped by runtime code).
```

2020-10-07 15:41 UTC, montogeek commented on src/content/configuration/target.md
> +- infer an environment (e.g: `last 2 node versions` the same as `target: "node"` with some [`output.environment`](/configuration/output/#outputenvironment) settings)
```suggestion
- Infer an environment (e.g: `last 2 node versions` the same as `target: "node"` with some [`output.environment`](/configuration/output/#outputenvironment) settings)
```

2020-10-07 15:41 UTC, montogeek commented on src/content/configuration/target.md
> +- infer an environment (e.g: `last 2 node versions` the same as `target: "node"` with some [`output.environment`](/configuration/output/#outputenvironment) settings)
```suggestion
- Infer an environment (e.g: `last 2 node versions` the same as `target: "node"` with some [`output.environment`](/configuration/output/#outputenvironment) settings).
```

2020-10-07 15:42 UTC, montogeek commented on src/content/configuration/target.md
> +Instructs webpack to target a specific environment. Defaults to `'browserslist'` or to `'web'` when no browserslist-config was found.
```suggestion
Instructs webpack to target a specific environment. Defaults to `'browserslist'` or to `'web'` when no browserslist configuration was found.
```

2020-10-07 15:43 UTC, montogeek commented on src/content/configuration/output.md
> +      // The environment supports EcmaScript Module syntax to import EcmaScript modules (import ... from '...').
```suggestion
      // The environment supports ECMAScript Module syntax to import ECMAScript modules (import ... from '...').
```

2020-10-07 22:00 UTC, montogeek approved these changes

2020-10-08 13:11 UTC, sokra approved these changes
There are still open things for `target`, but the changes are fine. More improvements in separate PR.

2020-10-08 13:11 UTC, merged

2020-10-08 13:12 UTC, sokra commented
Thanks