Dcoumented target option to revert to es5 syntax
webpack/webpack.js.org pull request #4017
Opened 2020-10-01 08:40 UTC by rramaa

`output.ecmaVersion` is removed in the release candidate
Documented the target option, through which the same thing can be achieved

2020-10-01 09:57 UTC, snitin315 commented on src/content/migrate/5.md
> +By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `config.target: ["web
```suggestion
By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `target: ["web", "es5"]` to revert to ES5 syntax (`web` if target environment is browser).
```

2020-10-02 16:43 UTC, rramaa commented
Some problem with the `licence/cla` check
I have contributed before @sokra

2020-10-02 16:50 UTC, evilebottnawi commented
Fixed

2020-10-03 18:55 UTC, rramaa commented
The build is failing
Seems some loaders are not found
Was working before
Need to update with master?

2020-10-04 13:24 UTC, snitin315 approved these changes

2020-10-07 08:40 UTC, EugeneHlushko requested changes

2020-10-07 08:40 UTC, EugeneHlushko commented on src/content/migrate/5.md
> +By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `target: ["web", "es5
```suggestion
By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `target: ['web', 'es5']` to revert to ES5 syntax (`web` if target environment is browser).
```

2020-10-07 08:42 UTC, EugeneHlushko commented on src/content/migrate/5.md
> +By default, webpack's runtime code uses ES2015 syntax to build smaller bundles. If your build targets environments that don't support this syntax (like IE11), you'll need to set `target: ["web", "es5
We are using single quotes in JS snippets in webpack.js.org, changing for consistency

2020-10-07 08:42 UTC, EugeneHlushko commented
Is this in-line with #4016 ?
CC @smelukov

2020-10-07 15:38 UTC, merged

2020-10-07 15:38 UTC, sokra commented
Thanks