update entry-advanced.md
webpack/webpack.js.org pull request #4174
Opened 2020-11-16 03:56 UTC by xp44mm

Complement and refine the operation steps.

2020-11-16 04:11 UTC, snitin315 requested changes
Few comments!

2020-11-16 04:11 UTC, snitin315 commented on src/content/guides/entry-advanced.md
> +npm install --save-dev webpack webpack-cli
I think we can skip these steps as covered in https://webpack.js.org/guides/installation/#local-installation

2020-11-16 04:11 UTC, snitin315 commented on src/content/guides/entry-advanced.md
> +npx webpack --config webpack.config.js
`webpack.config.js` is default

2020-11-16 04:11 UTC, snitin315 commented on src/content/guides/entry-advanced.md
> +npx webpack --config webpack.config.js
I think `npx webpack` suffices here.

2020-11-16 04:13 UTC, snitin315 commented on src/content/guides/entry-advanced.md
> +npm install --save-dev mini-css-extract-plugin
Usually, developers like to just copy-paste such commands. It will be great if we can merge these 3 commands into one.

2021-01-05 07:39 UTC, montogeek commented on src/content/guides/entry-advanced.md
> +First let's create a directory, initialize npm, [install webpack locally](/guides/installation/#local-installation), and install these tools:
```suggestion
First let's create a directory, initialize npm, [install webpack locally](/guides/installation/#local-installation), and install these dependencies:
```

2021-01-05 07:40 UTC, montogeek commented on src/content/guides/entry-advanced.md
> +Running webpack with above configuration, this run on windows system.
Not sure what do you want to express with this phrase.

2023-05-13 03:00 UTC, closed without merging