docs: add link for serve CLI options
webpack/webpack.js.org pull request #4611
Opened 2021-02-18 02:54 UTC by snitin315

To be merged after https://github.com/webpack/webpack-cli/pull/2438

2021-03-05 08:10 UTC, rishabh3112 requested changes

2021-03-05 08:10 UTC, rishabh3112 commented on src/content/configuration/dev-server.md
> +See a list of available CLI options for serve [here](https://github.com/webpack/webpack-cli/blob/master/SERVE.md)
```suggestion
List of CLI options for serve is available [here](https://github.com/webpack/webpack-cli/blob/master/SERVE.md)
```

2021-03-18 09:37 UTC, snitin315 commented on src/content/configuration/dev-server.md
> +See a list of available CLI options for serve [here](https://github.com/webpack/webpack-cli/blob/master/SERVE.md)
```suggestion
A list of CLI options for `serve` is available [here](https://github.com/webpack/webpack-cli/blob/master/SERVE-OPTIONS.md)
```

2021-03-19 01:42 UTC, snitin315 commented
/cc @chenxsan

2021-03-19 04:58 UTC, chenxsan approved these changes

2021-03-19 04:58 UTC, merged