Update noParse docs
webpack/webpack.js.org pull request #4908
Opened 2021-04-22 09:35 UTC by jakub-g

1) Warn about `[\\/]` for portability (`/` does not match on Windows)
2) Document `noParse` x `require`.

I had an issue like described with 3rd-party lib (webpack 4 was expanding `require('os')`, `require('http')` with shims).

One way to prevent expansion of `require`-s would be defining `externals`, one by one, but I think `noParse` is a better solution.

```
externals: {
    os: 'var {}',
    http: 'var {}',
    https: 'var {}',
},
```

2021-04-24 08:40 UTC, chenxsan commented
Can you share the `3rd-party lib` you mentioned so I can check? In addition, I noticed you mentioned webpack 4, are those changes for webpack 4 only? We have a https://github.com/webpack/webpack.js.org/tree/webpack-4 branch for webpack 4 documentation, and the master branch is kept for webpack 5.

2021-11-03 12:23 UTC, EugeneHlushko requested changes

2021-11-03 12:23 UTC, EugeneHlushko commented on src/content/configuration/module.mdx
> +For example, when building a project for browser target, and using a third-party library that was prebuilt as a dual browser/nodejs lib, and requires some nodejs built-ins, like `require('os')`.
```suggestion
For example, when building a project for `'browser'` [target](/configuration/target/) and using a third-party library that was prebuilt for both browser and Node.js and it requires Node.js built-ins e.g. `require('os')`.
```

2021-11-03 12:23 UTC, EugeneHlushko commented on src/content/configuration/module.mdx
> +`noParse` can be also used as a way to deliberately prevent  expansion of all `import`, `require`, `define` etc. calls, if you're sure those calls are unreachable at runtime.
```suggestion
`noParse` can be also used as a way to deliberately prevent expansion of all `import`, `require`, `define` etc. calls for cases when those calls are unreachable at runtime.
```

2021-11-03 12:23 UTC, EugeneHlushko commented on src/content/configuration/module.mdx
> +Note the need to use `[\\/]` in regex to match `\` on Windows and `/` on Mac/Linux.
```suggestion
T> You may need to use `[\\/]` in regex to match `\` on Windows and `/` on Mac/Linux.
```

2024-03-23 11:31 UTC, closed without merging