Patch 1
webpack/webpack.js.org pull request #6749
Opened 2023-04-08 06:46 UTC by long76

_describe your changes..._ 

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- **Remove these instructions from your PR as they are for your eyes only.**

[1]: https://github.com/openjs-foundation/EasyCLA#openjs-foundation-cla
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

2023-04-08 09:32 UTC, chenxsan commented
@TheLarkInn @alexander-akait Hey guys, it would be great if you could help review this pull request. I realized that I may have misunderstood something based on this comment: https://github.com/webpack/webpack.js.org/issues/6742#issuecomment-1500831469.

2023-04-18 01:22 UTC, TheLarkInn requested changes
Looks great! Just a few small wording changes and LGTM!

2023-04-18 01:22 UTC, TheLarkInn commented on src/content/configuration/output.mdx
> +Use a container(defined in global space) for call `define`/`require` functions in the AMD module.
```suggestion
Use a container(defined in global space) for calling `define`/`require` functions in an AMD module.
```

2023-04-18 01:22 UTC, TheLarkInn commented on src/content/configuration/output.mdx
> +W> Note that value of `amdContainer` **must be** set as global variable.
```suggestion
W> Note that the value of `amdContainer` **must be** set as a global variable.
```

2023-04-18 01:22 UTC, TheLarkInn commented on src/content/configuration/output.mdx
> +Which would result bundle like below:
```suggestion
Which will result in the following bundle:
```

2023-04-18 02:08 UTC, TheLarkInn approved these changes

2023-04-18 02:09 UTC, TheLarkInn commented
You can merge as you see fit @chenxsan. Thank you for the ping!

2023-04-18 02:23 UTC, merged

2023-04-18 04:45 UTC, long76 commented
Thanks!